#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
cp 0/K.org 0/K
cp 0/WInj1.org 0/WInj1
cp 0/WPro1.org 0/WPro1
runApplication setFields
runApplication darcyFoamD 

