//////////////////////////////////////// Inj1
coefQConstantInj1 = 1;
explicitSourceTermInj1 = ( coefQConstantInj1*SrcInj1*WInj1 )*activeWellInj1;
qWellInj1 = qConstantInj1;

///////////////////////////////////////// Pro1
coefQConstantPro1 = 1;
explicitSourceTermPro1 = -( coefQConstantPro1*SrcPro1*WPro1 )*activeWellPro1;
qWellPro1 = qConstantPro1;;
/////////////////////////////////////////

                                             
