#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


set -x

wmake libso porousModels

wmake libso porousBoundaryConditions

# ----------------------------------------------------------------- end-of-file
